const jewelList = [
  {
    id: 1,
    title: "Blue diamond Necklace",
    price: 2499,
    description: "Elegant handcrafted Kundan necklace for festive occasions.",
    category: "Necklace",
    section: "Sapphire",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500",
  },
  {
    id: 2,
    title: "Sapphire Silver Earrings",
    price: 1899,
    description: "Beautiful Kundan jhumkas with traditional detailing.",
    category: "Earrings",
    section: "Sapphire",
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=500",
  },
  {
    id: 3,
    title: "Gold Studs",
    price: 3299,
    description: "Premium Kundan choker set with matching earrings.",
    category: "Earrings",
    section: "Gold",
    image: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=500",
  },
  {
    id: 4,
    title: "bluestone crafted neck piece",
    price: 999,
    description: "Delicate Kundan maang tikka perfect for bridal looks.",
    category: "Necklace",
    section: "Sapphire",
    image: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=500",
  },
  {
    id: 5,
    title: "Gold pleated neck stack",
    price: 1599,
    description: "Elegant pearl and Kundan earrings for special occasions.",
    category: "Necklace",
    section: "Gold",
    image: "https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=500",
  },

  {
    id: 6,
    title: "Pearl Raindrop Necklace",
    price: 899,
    description: "Classic Maharashtrian Nath inspired by traditional designs.",
    category: "Necklace",
    section: "Pearl",
    image: "https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=500",
  },
  {
    id: 7,
    title: "Maharashtrian Nath",
    price: 2999,
    description: "Traditional Thushi necklace with an authentic Maharashtrian look.",
    category: "Nath",
    section: "Gold ",
    image: "../assets/nath.jpeg",
  },
  {
    id: 8,
    title: "Half moon Necklace",
    price: 3799,
    description: "Beautiful traditional Kolhapuri Saaj necklace.",
    category: "Necklace",
    section: "Gold",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500",
  },
  {
    id: 9,
    title: "Diamond Earrings",
    price: 1299,
    description: "Traditional Bugadi earrings inspired by Maharashtrian culture.",
    category: "Earrings",
    section: "Diamond",
    image: "https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=500",
  },
  {
    id: 10,
    title: "Gold pleated bracelet",
    price: 2699,
    description: "Classic Tanmani necklace with traditional Maharashtrian styling.",
    category: "Bracelet",
    section: "Bestsellers",
    image: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=500",
  },

  {
    id: 11,
    title: "Silver Dragon Chain Bracelet",
    price: 695,
    description: "Stylish silver bracelet from our latest collection.",
    category: "Bracelet",
    section: "NewArrival",
    image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=500",
  },
  {
    id: 12,
    title: "Gold Petite Micropave",
    price: 1680,
    description: "Elegant gold jewellery with delicate micropave detailing.",
    category: "Necklace",
    section: "NewArrival",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500",
  },
  {
    id: 13,
    title: "Rose Gold Ring",
    price: 1199,
    description: "Minimal heart pendant with a modern rose gold finish.",
    category: "Ring",
    section: "NewArrival",
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=500",
  },
  {
    id: 14,
    title: "Pearl Drop stack",
    price: 1399,
    description: "Modern pearl drop earrings suitable for everyday wear.",
    category: "Necklace",
    section: "NewArrival",
    image: "https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=500",
  },
  {
    id: 15,
    title: "Minimal Gold Chain",
    price: 1999,
    description: "Simple and elegant gold chain for everyday styling.",
    category: "Necklace",
    section: "NewArrival",
    image: "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=500",
  },
  {
    id: 16,
    title: "Silver Floral Bracelet",
    price: 899,
    description: "Delicate floral bracelet with a polished silver finish.",
    category: "Bracelet",
    section: "NewArrival",
    image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=500",
  },

  {
    id: 17,
    title: "Kundan Statement Necklace",
    price: 3499,
    description: "A beautiful statement necklace perfect for weddings and parties.",
    category: "Necklace",
    section: "BestSellers",
    image: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=500",
  },
  {
    id: 18,
    title: "Pearl drop Necklace",
    price: 799,
    description: "One of our most popular traditional Maharashtrian jewellery pieces.",
    category: "Necklace",
    section: "BestSellers",
    image: "https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=500",
  },
  {
    id: 19,
    title: "Diamond Earrings",
    price: 1599,
    description: "Elegant pearl and Kundan earrings for special occasions.",
    category: "Earrings",
    section: "BestSellers",
    image: "https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=500",
  },
  {
    id: 20,
    title: "chain Bracelet",
    price: 4299,
    description: "Traditional bridal necklace inspired by Maharashtrian jewellery.",
    category: "Bracelet",
    section: "BestSellers",
    image: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=500",
  },
  {
    id: 21,
    title: "Classic Bangle",
    price: 2299,
    description: "Elegant classic bangle that complements traditional and modern outfits.",
    category: "Bangle",
    section: "BestSellers",
    image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=500",
  },
  {
    id: 22,
    title: "Cocktail Ring",
    price: 1299,
    description: "Statement Kundan ring designed for festive occasions.",
    category: "Ring",
    section: "BestSellers",
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=500",
  },
  {
    id: 23,
    title: "Layered Necklace",
    price: 2799,
    description: "Elegant layered pearl necklace with a sophisticated finish.",
    category: "Necklace",
    section: "BestSellers",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500",
  },
  {
    id: 24,
    title: "chandni Earrrings",
    price: 1799,
    description: "Classic gold jhumkas loved for their timeless traditional design.",
    category: "Earrings",
    section: "BestSellers",
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=500",
  },
  {
    id: 25,
    title: "Minimal Neckpiece",
    price: 1499,
    description: "Beautiful bridal Nath featuring a traditional Maharashtrian design.",
    category: "Neckpiece",
    section: "BestSellers",
    image: "https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=500",
  },
];

export default jewelList;